### ISSUE TITLE
New system themes

### ISSUE THREAD

**Issue by QKillerQ** [lehcimcramtrebor/es-theme-HEXA#2]
Hi!

I'm using your theme in RetroBat - and it's the absolute best! I have created a few systems of my own that you didn't have included (Singe, Zinc, etc.). Are you interested in those? I would love to contribute. Thanks!

**Comment by lehcimcramtrebor** [comment]
Hi, all depends of visual of tiles. Join us in retrobat discord if you want to show your work.. so if visual is not as I wait, I can add your systems to « todo list ».. https://discord.gg/uyrZrKKDeR

**Comment by QKillerQ** [comment]
Thanks! I posted them there just now.
