### ISSUE TITLE
New option: Description delay

### ISSUE THREAD

**Issue by Planetdune** [lehcimcramtrebor/es-theme-HEXA#3]
Hello there, this is a great theme! A small thing, I do not use the image that shows just before it displays the description text of a game. (I think it is the marquee one). This works but the description when changing titles waits like a second before showing (the time it takes to now show an image that is not there). Would it be possible to have an option that it instantly displays? (or make it so it does if the logo is not present).

If this is not possible for the entire release, would it be possible for me to personally edit some file to get this result?

Thank you again!

**Comment by lehcimcramtrebor** [comment]
Hello, i have added a default es icon as default marquee, so this icon is displayed before description when no marquee are used. i can't do differently because many things in code are dependants of this.
