### ISSUE TITLE
New "systems" request

### ISSUE THREAD

**Issue by Planetdune** [lehcimcramtrebor/es-theme-HEXA#4]
Hello,

We all know this theme is great, I have two romsets working that do not have any images in Hexa.

- Windows 3.11
- Nintendo 3DS (eshop)

There is a "Windows" but it is obviously meant for modern Windows games. Not the Win3.x era.
There is a "PSPMinis" so the Nintendo 3DS eshop would be in the same vein.

If that would be possible, that would be great!

Thanks!

**Comment by lehcimcramtrebor** [comment]
Hi, added w311 and neshop.. let me know if namig is good.
